CREATE DATABASE IF NOT EXISTS SupermarketDB;
USE SupermarketDB;
CREATE TABLE Customer (
  cID VARCHAR(10) PRIMARY KEY,
  cName VARCHAR(100),
  cAge INT
);
CREATE TABLE Product (
  pID VARCHAR(10) PRIMARY KEY,
  pName VARCHAR(100),
  pPrice DECIMAL(10,2)
);
CREATE TABLE `Order` (
  oID VARCHAR(10) PRIMARY KEY,
  cID VARCHAR(10),
  oDate DATE,
  oTotalPrice DECIMAL(10,2),
  FOREIGN KEY (cID) REFERENCES Customer(cID)
);
CREATE TABLE OrderDetail (
  oID VARCHAR(10),
  pID VARCHAR(10),
  odQTY INT,
  PRIMARY KEY (oID, pID),
  FOREIGN KEY (oID) REFERENCES `Order`(oID),
  FOREIGN KEY (pID) REFERENCES Product(pID)
);